version: '3.8'
services:
  mysql:
    container_name: mysql
    image: mysql:8.0.1
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: petcare
      MYSQL_ROOT_PASSWORD: root
    networks:
      - pet_network

  spring-app:
    container_name: app
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - "MYSQL_DB_SERVER_ADDRESS=mysql"
      - "MYSQL_DB_SERVER_PORT=3306"
      - "MYSQL_USER=root"
      - "MYSQL_ROOT_PASSWORD=root"
    depends_on:
      - mysql
    networks:
      - pet_network

networks:
  pet_network:
    external: true

