server:
  port: 8080

#spring:
#  application:
#    name: petcare
#  datasource:
#    url: jdbc:mysql://root:sTpcwvTGRuZrfBRvZhBnYGZnFUXJdiMe@roundhouse.proxy.rlwy.net:17966/railway?allowPublicKeyRetrieval=true&useSSL=false
#    driverClassName: "com.mysql.cj.jdbc.Driver"
#    username: root
#    password: sTpcwvTGRuZrfBRvZhBnYGZnFUXJdiMe
spring:
  application:
    name: petcare
  datasource:
    url: jdbc:mysql://${MYSQL_DB_SERVER_ADDRESS:localhost}:${MYSQL_DB_SERVER_PORT:3306}/${MYSQL_DATABASE:petcare}?allowPublicKeyRetrieval=true&useSSL=false
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${MYSQL_USER:root}
    password: ${MYSQL_ROOT_PASSWORD:Tien19101976}
  jpa:
    hibernate:
      ddl-auto: update
      # ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
springdoc:
  api-docs:
    path: /api-docs
jwt:
  signerKey: VtvtKZR9eC/X+lTaid8HwiYz+RitST7PiPcLlu5WSqdyMfhiLy+OhCjdR0zjd0PE
  issuer: "dev.com"


